# Generated by Django 5.1.5 on 2025-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_alter_buyer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
