# Generated by Django 5.1.5 on 2025-01-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titel',
            new_name='title',
        ),
    ]
