# Generated by Django 5.1.5 on 2025-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_rename_titel_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
